name: 🚀 Production Pipeline

on:
  repository_dispatch:
    types: [promote-to-prod]

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          ref: test
          fetch-depth: 0

      - name: 🔄 Promote test → main
        run: |
          echo "Promoting test → main (production)..."
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin '+refs/heads/*:refs/remotes/origin/*'
          git checkout -B main origin/main
          git merge origin/test --no-ff -m "Auto merge from test to prod [skip ci]"
          git push origin main

      - name:  Deployment placeholder
        run: |
          echo "This is where deployment (e.g., Vercel/Azure) would occur."
          echo "Main branch is now production-ready."
